name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  smoke-test:
    name: 'Library Smoke Test'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Library smoke test
      run: |
        npm run build
        npm test
        echo "✅ Library smoke test passed"

  action-test:
    name: 'GitHub Action Test'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create realistic test HTML
      run: |
        mkdir -p test-html/
        cat > test-html/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <title>Test Module</title>
          <link rel="stylesheet" href="Agda.css">
        </head>
        <body>
          <h1>Test Module</h1>
          <div class="body">
            <pre class="Agda">
              <a id="1" class="Symbol">{-#</a> <a id="4" class="Keyword">OPTIONS</a> <a id="12" class="Pragma">--safe</a> <a id="19" class="Symbol">#-}</a>
              <a id="23" class="Keyword">module</a> <a id="30" class="Module">Test</a> <a id="35" class="Keyword">where</a>

              <a id="42" class="Keyword">data</a> <a id="47" class="Datatype">ℕ</a> <a id="49" class="Symbol">:</a> <a id="51" class="PrimitiveType">Set</a> <a id="55" class="Keyword">where</a>
                <a id="63" class="InductiveConstructor">zero</a> <a id="68" class="Symbol">:</a> <a id="70" class="Datatype">ℕ</a>
                <a id="74" class="InductiveConstructor">suc</a>  <a id="79" class="Symbol">:</a> <a id="81" class="Datatype">ℕ</a> <a id="83" class="Symbol">→</a> <a id="85" class="Datatype">ℕ</a>
            </pre>
          </div>
        </body>
        </html>
        EOF

    - name: Create minimal test config
      run: |
        cat > test-config.json << 'EOF'
        {
          "githubUrl": "https://github.com/will-break-it/agda-web-docs-lib",
          "modules": ["Test"],
          "inputDir": "test-html/"
        }
        EOF

    - name: Test GitHub Action
      uses: ./
      with:
        input-dir: 'test-html/'
        github-url: 'https://github.com/will-break-it/agda-web-docs-lib'
        modules: 'Test'
        config-file: 'test-config.json'

    - name: Validate transformation
      run: |
        echo "Checking transformed HTML..."
        
        # First, list what's actually in the directory
        echo "Contents of test-html/:"
        ls -la test-html/
        
        # Show the HTML content to see what was transformed
        echo "HTML content after transformation:"
        cat test-html/index.html
        
        # Check that CSS files were copied
        if [ ! -f "test-html/base.css" ]; then
          echo "❌ base.css not found"
          exit 1
        fi
        
        # Check that JS files were copied  
        if [ ! -f "test-html/themeInit.js" ]; then
          echo "❌ themeInit.js not found"
          exit 1
        fi
        
        # Check that HTML was transformed (should have theme scripts)
        if ! grep -q 'themeInit.js' test-html/index.html; then
          echo "❌ Theme script not linked"
          exit 1
        fi
        
        # Check for search functionality
        if ! grep -q 'search.js' test-html/index.html; then
          echo "❌ Search script not linked"
          exit 1
        fi
        
        echo "✅ GitHub Action test passed" 