name: 'Transform Agda Documentation'

on:
  workflow_call:
    inputs:
      input-dir:
        description: 'Directory containing HTML files to transform'
        required: true
        type: string
      output-dir:
        description: 'Output directory (defaults to in-place transformation)'
        required: false
        type: string
        default: ''
      config-file:
        description: 'Path to agda-docs config file'
        required: false
        type: string
        default: 'agda-docs.config.json'
      back-button-url:
        description: 'URL for the back button'
        required: false
        type: string
        default: ''
      modules:
        description: 'Comma-separated module prefixes'
        required: false
        type: string
        default: ''
      github-url:
        description: 'GitHub repository URL for source links'
        required: false
        type: string
        default: ''
      artifact-name:
        description: 'Name for uploaded artifact'
        required: false
        type: string
        default: 'agda-docs-transformed'

    outputs:
      files-processed:
        description: 'Number of HTML files processed'
        value: ${{ jobs.transform.outputs.files-processed }}
      output-directory:
        description: 'Directory containing transformed files'
        value: ${{ jobs.transform.outputs.output-directory }}

jobs:
  transform:
    runs-on: ubuntu-latest
    outputs:
      files-processed: ${{ steps.transform.outputs.files-processed }}
      output-directory: ${{ steps.transform.outputs.output-directory }}
    
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🔄 Transform Agda documentation
        id: transform
        uses: will-break-it/agda-web-docs-lib@v0.7.1
        with:
          input-dir: ${{ inputs.input-dir }}
          output-dir: ${{ inputs.output-dir }}
          config-file: ${{ inputs.config-file }}
          back-button-url: ${{ inputs.back-button-url }}
          modules: ${{ inputs.modules }}
          github-url: ${{ inputs.github-url }}

      - name: 📤 Upload transformed documentation
        if: steps.transform.outputs.files-processed > 0
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ steps.transform.outputs.output-directory }}

      - name: ✅ Summary
        run: |
          echo "🎉 Transformation complete!"
          echo "Files processed: ${{ steps.transform.outputs.files-processed }}"
          echo "Output directory: ${{ steps.transform.outputs.output-directory }}" 